## Rotation Matrix 2D
---
### Rumus
$$
\begin{bmatrix} 
{x}' \\ {y}' 
\end{bmatrix}
=
\begin{bmatrix} 
\cos \theta & -\sin \theta 
\\ \sin\theta & \cos\theta 
\end{bmatrix} 
\begin{bmatrix} x \\ y \end{bmatrix}
$$

#### Contoh 1
Diketahui:

$
P(x,y) = (1,1)
$

$
\theta = 30^\circ
$

Posisi Akhir
$
P'(x',y') = (?,?)
$

In [9]:
import numpy as np
theta = 30.0
x = 1
y = 1
P = np.array([[x],
             [y]]) #Posisi Awal P
print("P = \n" ,P)

theta = theta / 180 * np.pi
print("Theta dalam radian = " ,theta)

rot = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta), np.cos(theta)]])
print("Matriks rotasi: \n" ,rot)

P2 = rot.dot(P)
x2 = P2[0,0]
y2 = P2[1,0]
print("P' =\n" ,P2)
print("x' = " ,x2)
print("y' = " ,y2)

P = 
 [[1]
 [1]]
Theta dalam radian =  0.5235987755982988
Matriks rotasi: 
 [[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]
P' =
 [[0.3660254]
 [1.3660254]]
x' =  0.36602540378443876
y' =  1.3660254037844386


#### Contoh 2
Diketahui:

Posisi akhir
$
P'(x',y') = (3,4)
$

$
\theta = -15^\circ
$

Posisi Awal
$
P(x,y) = (?,?)
$

In [1]:
import numpy as np
theta = -15.0
x2 = 3
y2 = 4
P2 = np.array([[x2],
              [y2]]) #Posisi Akhir P'
print("P' = \n" ,P2)

theta = theta / 180 * np.pi
print("Theta dalam radian = " ,theta)

rot = np.array([[np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]])
print("Matriks rotasi: \n" ,rot)
rot = np.linalg.inv(rot)
print("Invers Matriks rotasi: \n" ,rot)

P = rot.dot(P2)
x = P[0,0]
y = P[1,0]
print("P = \n" ,P)
print("x = " ,x)
print("y = " ,y)

P' = 
 [[3]
 [4]]
Theta dalam radian =  -0.2617993877991494
Matriks rotasi: 
 [[ 0.96592583  0.25881905]
 [-0.25881905  0.96592583]]
Invers Matriks rotasi: 
 [[ 0.96592583 -0.25881905]
 [ 0.25881905  0.96592583]]
P = 
 [[1.8625013 ]
 [4.64016044]]
x =  1.8625012984571216
y =  4.640160440463836
